baseURL = "https://www.foret-de-berce.fr/"
languageCode = "fr-FR"
title = "Bercé, une forêt d'exception"
theme = "ananke"
canonifyURLs = true
copyright = "Yves GOUCHET"
googleAnalytics = "UA-151972727-1"
enableRobotsTXT = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 9


[params]
  featured_image = "/images/foret-de-berce.jpg"