baseURL = "https://www.foret-de-berce.fr/"
languageCode = "fr-FR"
title = "Bercé, une forêt d'exception"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = "UA-151972727-1"
enableRobotsTXT = true